config/routes.rb
Rails.application.routes.draw do
  resources :vocabulary_lists # do
  #   post 'import', on: :member
  # end

  root to: 'beta/beta#index'
  namespace :beta do
    resources :users, only: [:new, :create]
    get 'thank_you', to: 'beta#thank_you'
  end

  #get 'products/:id', to: 'products#show', :as => :products
  #devise_for :users
  #resources :users
end

app/models/vocabulary_list.rb
class VocabularyList < ActiveRecord::Base
  extend SpreadsheetHelper

  attr_accessor :word_list_file

  has_many :vocabulary_list_words, :inverse_of => :vocabulary_list, :dependent => :destroy
  accepts_nested_attributes_for :vocabulary_list_words, allow_destroy: true

  validates :name, :group, :description, presence: true
  validates_associated :vocabulary_list_words

  before_validation :import_word_list_from_file, if: "word_list_file.present?"

  private

  def import_word_list_from_file
    spreadsheet = VocabularyList.open_spreadsheet word_list_file
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      vocabulary_list_word_atts = row.to_hash.slice(*VocabularyListWord.new.attributes.keys)
      if self.vocabulary_list_words.find_by(vocabulary_list_word_atts).blank?
        self.vocabulary_list_words.build(vocabulary_list_word_atts)
      end
    end
  end

end

app/controllers/vocabulary_lists_controller.rb
class VocabularyListsController < ApplicationController
  before_action :set_vocabulary_list, only: [:show, :edit, :update, :destroy]

  # GET /vocabulary_lists
  # GET /vocabulary_lists.json
  def index
    @vocabulary_lists = VocabularyList.all
  end

  # GET /vocabulary_lists/1
  # GET /vocabulary_lists/1.json
  def show
  end

  # GET /vocabulary_lists/new
  def new
    @vocabulary_list = VocabularyList.new
  end

  # GET /vocabulary_lists/1/edit
  def edit
  end

  # POST /vocabulary_lists
  # POST /vocabulary_lists.json
  def create
    puts "vocabulary_list_params=#{vocabulary_list_params.inspect}"
    @vocabulary_list = VocabularyList.new(vocabulary_list_params)

    respond_to do |format|
      if @vocabulary_list.save
        format.html { redirect_to vocabulary_lists_path, notice: 'Vocabulary list was successfully created.' }
        format.json { render :show, status: :created, location: @vocabulary_list }
      else
        format.html { render :new }
        format.json { render json: @vocabulary_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vocabulary_lists/1
  # PATCH/PUT /vocabulary_lists/1.json
  def update
    respond_to do |format|
      if @vocabulary_list.update(vocabulary_list_params)
        format.html { redirect_to @vocabulary_list, notice: 'Vocabulary list was successfully updated.' }
        format.json { render :show, status: :ok, location: @vocabulary_list }
      else
        format.html { render :edit }
        format.json { render json: @vocabulary_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vocabulary_lists/1
  # DELETE /vocabulary_lists/1.json
  def destroy
    @vocabulary_list.destroy
    respond_to do |format|
      format.html { redirect_to vocabulary_lists_url, notice: 'Vocabulary list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vocabulary_list
      @vocabulary_list = VocabularyList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vocabulary_list_params
      params.require(:vocabulary_list).permit(:name, :group, :description, :word_list_file)
    end
end

app/helpers/vocabulary_lists_helper.rb
module VocabularyListsHelper
end

app/views/vocabulary_lists/_form.html.haml
.text-center.p-sm
  = bootstrap_form_for @vocabulary_list, feedback_icons: true, inline_errors: false, tooltip_errors: 'bottom', layout: :horizontal, label_col: "col-sm-3", control_col: "col-sm-9", multipart: true do |f|
    - if @vocabulary_list.errors.any?
      .small.text-left
        = f.alert_message 'Please fill in all the required fields and fix the errors below.', error_summary: true
    = f.text_field :name, placeholder: 'Level 1'
    = f.text_field :group, placeholder: 'Oxford 3000 Nouns'
    = f.text_area :description, placeholder: 'Nouns from the Oxford 3000'
    = f.file_field :word_list_file, label: "Word List File"
    = f.primary 'Save'


-#= form_for @vocabulary_list do |f|
-#  - if @vocabulary_list.errors.any?
-#    #error_explanation
-#      %h2= "#{pluralize(@vocabulary_list.errors.count, "error")} prohibited this vocabulary_list from being saved:"
-#      %ul
-#        - @vocabulary_list.errors.full_messages.each do |msg|
-#          %li= msg
-#
-#  .field
-#    = f.label :name
-#    = f.text_field :name
-#  .field
-#    = f.label :group
-#    = f.text_field :group
-#  .field
-#    = f.label :description
-#    = f.text_area :description
-#  .actions
-#    = f.submit 'Save'

app/views/vocabulary_lists/_vocabulary_list.html.haml
= render 'form'

app/views/vocabulary_lists/edit.html.haml
%h1 Editing vocabulary_list

= render 'form'

= link_to 'Show', @vocabulary_list
\|
= link_to 'Back', vocabulary_lists_path

app/views/vocabulary_lists/index.html.haml
- @sidebar = 'user'
.row
  .col-sm-12
    %h1 Vocabulary Lists
.row
  .col-sm-12
    .dataTable_wrapper
      %table#datatable.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th Name
            %th Group
            %th Description
            %th Updated
            /%th P
            /%th D
            /%th A

        %tbody
          - @vocabulary_lists.each do |vocabulary_list|
            %tr
              %td= vocabulary_list.name
              %td= vocabulary_list.group
              %td= vocabulary_list.description
              %td= vocabulary_list.updated_at
              /%td= link_to 'Show', vocabulary_list
              /%td= link_to 'Edit', edit_vocabulary_list_path(vocabulary_list)
              /%td= link_to 'Destroy', vocabulary_list, :method => :delete, :data => { :confirm => 'Are you sure?' }
    = link_to 'Create New', new_vocabulary_list_path, role: 'button', class: 'btn btn-primary'

app/views/vocabulary_lists/new.html.haml
- @sidebar = 'user'
.row
  .col-md-12
    %h1
      New Vocabulary List
  .col-md-6
    .panel.panel-default
      .panel-body
        = render partial: 'vocabulary_list'
  .col-md-12
    = link_to 'Back', vocabulary_lists_path

app/views/vocabulary_lists/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @vocabulary_list.name
%p
  %b Group:
  = @vocabulary_list.group
%p
  %b Description:
  = @vocabulary_list.description

= link_to 'Edit', edit_vocabulary_list_path(@vocabulary_list)
\|
= link_to 'Back', vocabulary_lists_path