config/routes.rb
Rails.application.routes.draw do
  resources :vocabulary_lists # do
  #   post 'import', on: :member
  # end

  root to: 'beta/beta#index'
  namespace :beta do
    resources :users, only: [:new, :create]
    get 'thank_you', to: 'beta#thank_you'
  end

  #get 'products/:id', to: 'products#show', :as => :products
  #devise_for :users
  #resources :users
end

app/controllers/beta/beta_controller.rb
class Beta::BetaController < ApplicationController
end

app/controllers/beta/users_controller.rb
class Beta::UsersController < ApplicationController
  # GET /beta/users/new
  def new
    @user = User.new
    UserSurvey::SURVEY_QUESTIONS.keys.each { |kode| @user.user_surveys.build(code: kode) }
  end

  # POST /beta/users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to beta_thank_you_path, notice: 'User successfully registered for beta.' }
      else
        #flash[:notice] = 'Some of the fields have errors.'
        format.html { render action: 'new' }
      end
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone, user_surveys_attributes: [ :code, :answer ])
  end
end

app/views/beta/beta/index.html.haml
/- @sidebar = 'user'
.row
  .col-sm-12
    .jumbotron.text-center
      %h1 Never forget vocabulary words again!
      %p Learn how to study more efficiently with Smart Gongbu.
      .row
        .col-sm-12
          #video_link
            = icon 'play-circle', class: 'fa-5x'
          #video_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
            .modal-dialog
              .modal-content
                .modal-header
                  %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
                .modal-body
                  .embed-responsive.embed-responsive-16by9
                    %iframe.embed-responsive-item{:allowfullscreen => "", :frameborder => "0", :height => "315", :width => "560"}
    %h1 Beta Signup!
    %p Smart Gongbu is still in development, but will be available very soon. Sign-up today and be the first to test Smart Gongbu!
    = link_to 'Sign up for Beta Test', new_beta_user_path, role: 'button', class: 'btn btn-primary btn-lg'

app/views/beta/beta/thank_you.html.haml
.row
  .col-sm-12
    %h1 Thank you for signing up!
    %p You will recieve an email from us when Smart Gongbu is ready to be beta tested!
    = link_to 'Back to Smart Gongbu', root_path, role: 'button', class: 'btn btn-primary btn-lg'