config/routes.rb
Rails.application.routes.draw do
  resources :vocabulary_lists # do
  #   post 'import', on: :member
  # end

  root to: 'beta/beta#index'
  namespace :beta do
    resources :users, only: [:new, :create]
    get 'thank_you', to: 'beta#thank_you'
  end

  #get 'products/:id', to: 'products#show', :as => :products
  #devise_for :users
  #resources :users
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-inverse.navbar-static-top{:role => 'navigation', :style => 'margin-bottom: 0'}
  -# .container
  .navbar-header
    %button.navbar-toggle{'data-target' => '.navbar-collapse', 'data-toggle' => 'collapse', :type => 'button'}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to 'Smart Gongbu', root_path, class: 'navbar-brand'
  .collapse.navbar-collapse
    %ul.nav.navbar-nav.navbar-right
      = render 'layouts/navigation_top_links'
  - if @sidebar
    .navbar-inverse.sidebar{:role => "navigation"}
      .sidebar-nav.navbar-collapse
        %ul#side-menu.nav
          = render 'layouts/navigation_sidebar_menu'

app/views/layouts/_navigation_sidebar_menu.html.haml
%li
  = link_to(root_path) do
    = icon 'dashboard', 'Dashboard', class: 'fa-fw'
%li
  = link_to('#') do
    = icon 'bar-chart-o', 'Charts', class: 'fa-fw'
    = content_tag 'span', icon('arrow')
  %ul.nav.nav-second-level
    %li= link_to('Flot Charts', root_path)
    %li= link_to('Morris.js Charts', root_path)

app/views/layouts/_navigation_top_links.html.haml
%li{:role => 'presentation'}
  = link_to(root_path) do
    = icon 'cog', 'SUPPORT', class: 'fa-fw fa-inverse'
%li{:role => 'presentation'}
  = link_to(root_path) do
    = icon 'phone', 'CONTACT', class: 'fa-fw fa-inverse'
%li{:role => 'presentation', :class => 'dropdown'}
  %a{ :href => '#', :class => 'dropdown-toggle', :data => { :toggle => 'dropdown' }, :aria => { :expanded => 'false' } }
    = icon 'user', class: 'fa-fw fa-inverse'
    = icon 'caret-down', class: 'fa-inverse'
  %ul.dropdown-menu.dropdown-user
    %li
      = link_to(root_path) do
        = icon 'sign-in', 'Login', class: 'fa-fw'
    %li
      = link_to(root_path) do
        = icon 'user', 'User Profile', class: 'fa-fw'

-# - if user_signed_in?
  %li= link_to 'Edit account', edit_user_registration_path
  %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
-# - else
  %li= link_to 'Sign in', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path
-# - if user_signed_in?
  - if current_user.try(:admin?)
    %li= link_to 'Admin', '/admin'
    %li= link_to 'Users', users_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Smart Gongbu'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Smart Gongbu - Never forget vocabulary words again!'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag params[:controller], media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
    %main{:role => "main"}
      #wrapper
        = render 'layouts/navigation'
        %div{ :id => (@sidebar ? 'page-wrapper' : 'page-wrapper-full')}
          / = render 'layouts/messages'
          = yield
    = javascript_include_tag params[:controller], 'data-turbolinks-track' => true